### ISSUE TITLE
This repo needs readme

### ISSUE THREAD

**Issue by Hameds** [ahmadmo/fast-data-examples#1]
<div dir="rtl">

من در توییتر درباره کاری که قصد دارید اینجا انجام بشه خوندم. به نظرم یک readme کمک می‌کنه که با توضیح درباره هدف این مخزن، مشارکت شکل بگیره

</div>

**Comment by ahmadmo** [comment]
<body>
<div>
<p dir="rtl">
بله به زودی README مفصلی براش آماده میکنم
</p>
</div>
<body>
